# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres,
      POSTGRES_PASSWORD: password
